version: "3.9"
services:
  node:
    build: .
    image: cbt-tools-node:latest
    environment:
      - PORT=3000
      - PDF2MARKDOWN_BASE_URL=http://dc-pdf2markdown:3000
      - TOOLS_PASSWORD=${TOOLS_PASSWORD}
    volumes:
      - database:/app/database
    ports:
      - "80:3000"
  dc-pdf2markdown:
    build:
      context: ./dc-pdf2markdown
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - STORAGE_ROOT=/temp/storage
      - DISABLE_JOB_SCANNER=true
    volumes:
      - ./storage:/temp/storage
volumes:
  database: {}